# name: Full CD Pipeline

# on:
#   push:
#     branches: [ "main" ]
#     paths:
#       - 'web/**'
#       - 'api/**'

# jobs:

#   ## CD for Web Frontend
#   deploy-web:
#     runs-on: ubuntu-latest
#     defaults:
#       run:
#         working-directory: web
#     steps:
#       - uses: actions/checkout@v4

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v3

#       - name: Log in to DockerHub
#         uses: docker/login-action@v3
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}

#       - name: Build & Push Web Docker Image
#         run: |
#           docker build -t ${{ secrets.DOCKER_USERNAME }}/web-frontend:latest .
#           docker push ${{ secrets.DOCKER_USERNAME }}/web-frontend:latest


#   ## CD for Backend API
#   deploy-backend:
#     runs-on: ubuntu-latest
#     defaults:
#       run:
#         working-directory: api
#     steps:
#       - uses: actions/checkout@v4

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v3

#       - name: Log in to DockerHub
#         uses: docker/login-action@v3
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}

#       - name: Build & Push Backend Docker Image
#         run: |
#           docker build -t ${{ secrets.DOCKER_USERNAME }}/fastapi-backend:latest .
#           docker push ${{ secrets.DOCKER_USERNAME }}/fastapi-backend:latest
