# name: Full CI Pipeline

# on:
#   pull_request:
#     branches: [ "main" ]
#     paths:
#       - 'web/**'
#       - 'crm-mobile/**'
#       - 'api/**'
#   push:
#     branches: [ "main" ]
#     paths:
#       - 'web/**'
#       - 'crm-mobile/**'
#       - 'api/**'

# jobs:

#   ## Web Frontend (React)
#   web-frontend:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         node-version: [18.x, 20.x, 22.x]
#     defaults:
#       run:
#         working-directory: web
#     steps:
#       - uses: actions/checkout@v4
#       - name: Setup Node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@v4
#         with:
#           node-version: ${{ matrix.node-version }}
#           cache: 'npm'
#           cache-dependency-path: web/package-lock.json

#       - name: Install Dependencies
#         run: npm ci

#       - name: Build React App
#         run: npm run build --if-present

#       - name: Run Tests
#         run: npm test


#   ## Mobile App (React Native)
#   mobile-frontend:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         node-version: [18.x, 20.x, 22.x]
#     defaults:
#       run:
#         working-directory: crm-mobile
#     steps:
#       - uses: actions/checkout@v4
#       - name: Setup Node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@v4
#         with:
#           node-version: ${{ matrix.node-version }}
#           cache: 'npm'
#           cache-dependency-path: crm-mobile/package-lock.json

#       - name: Install Dependencies
#         run: npm ci

#       - name: Lint Mobile App
#         run: npm run lint || true  # Optional: allow non-blocking lint errors



#   ## Backend API (FastAPI)
#   backend-api:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         python-version: [3.10, 3.11, 3.13.5]
#     defaults:
#       run:
#         working-directory: api
#     steps:
#       - uses: actions/checkout@v4

#       - name: Set up Python ${{ matrix.python-version }}
#         uses: actions/setup-python@v5
#         with:
#           python-version: ${{ matrix.python-version }}

#       - name: Install Dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt

#       - name: Run Backend Tests
#         run: pytest

