name: Web Frontend CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'web/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'web/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: web/package-lock.json

    - name: Install dependencies
      working-directory: ./web
      run: npm ci

    - name: Build (if present)
      working-directory: ./web
      run: npm run build --if-present

    - name: Run tests
      working-directory: ./web
      run: npm test
